# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')

setup(
    long_description=readme,
    name='fastx',
    version='0.0.1',
    description='fastx',
    python_requires='==3.*,>=3.6.1',
    project_urls={
        "documentation": "https://fastx.readthedocs.io",
        "homepage": "https://github.com/Sangjin/fastx",
        "repository": "https://github.com/Sangjin/fastx"
    },
    author='Sangjin Lee',
    author_email='sl17@sanger.ac.uk',
    license='MIT',
    classifiers=[
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8'
    ],
    entry_points={"console_scripts": ["fastx = fastx.__main__:main"]},
    packages=['fastx'],
    package_dir={"": "src"},
    package_data={"fastx": ["*.typed"]},
    install_requires=[
        'argparse==1.*,>=1.4.0', 'bio==0.*,>=0.4.1', 'click==7.*,>=7.0.0',
        'pysam==0.*,>=0.16.0'
    ],
    extras_require={
        "dev": [
            "coverage[toml]==5.*,>=5.1.0", "mypy==0.*,>=0.780.0",
            "pre-commit==2.*,>=2.5.1", "pytest==5.*,>=5.4.3",
            "safety==1.*,>=1.9.0", "sphinx==3.*,>=3.1.0",
            "sphinx-autobuild==0.*,>=0.7.1", "typeguard==2.*,>=2.9.1",
            "xdoctest==0.*,>=0.12.0"
        ]
    },
)
